apiVersion: apps/v1
kind: ReplicaSet
metadata:
        name: myweb-rs
spec:
        replicas: 3
        selector:
                matchExpressions:
                        - {key: env,operator: In,values: [production]}
                        - {key: region,operator: In,values: [INDIA]}
        template:
                metadata:
                        name: myweb-prod
                        labels:
                                env: production
                                region: INDIA
                spec:
                        containers:
                                - name: myweb-container
                                  image: httpd

